on : push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
   
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp-nathand59.alwaysdata.net
        username: nathand59_test
        password: ${{ secrets.ftp_password }}
        server-dir: /home/nathand59/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/bootstrap/scss/**
          **/node_modules/bootstrap/js/**
          **/node_modules/bootstrap-icons/icons/**  
        
